# Generated by Django 4.0.5 on 2022-09-16 10:42

from django.db import migrations

import immunity_radius.base.validators
import immunity_utils.fields
from immunity_radius import settings as app_settings


class Migration(migrations.Migration):

    dependencies = [
        ('immunity_radius', '0032_organizationradiussettings_sms_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='password_reset_url',
            field=immunity_utils.fields.FallbackCharField(
                blank=True,
                default=app_settings.DEFAULT_PASSWORD_RESET_URL,
                fallback=app_settings.DEFAULT_PASSWORD_RESET_URL,
                help_text='Enter the URL where users can reset their password',
                max_length=200,
                null=True,
                validators=[
                    immunity_radius.base.validators.password_reset_url_validator
                ],
                verbose_name='Password reset URL',
            ),
        ),
    ]
